### ISSUE TITLE
Upgrade Python interpreter in Drone runner image

### ISSUE THREAD

**Issue by danielchg** [konstellation-io/science-toolkit#119]
Solicitud:
Imagen (terminus7/sci-toolkit-runner:latest) con la GPU configurada y versión de python 3.8.7 o bien 3.9.2.

Upgrade Python interpretor to version 3.8.7 or 3.9.2 in order to have better support of multiproccesing.

**Comment by aacecandev** [comment]
This issue was closed with #158
