### ISSUE TITLE
Update Gitea version to 1.14

### ISSUE THREAD

**Issue by danielchg** [konstellation-io/science-toolkit#138]
There are a new release of Gitea with interesting new features in the API and some bug fixes

**Comment by danielchg** [comment]
looks like everything works fine except the permissions update from kdl front

**Comment by angelsanchez** [comment]
The repository migration used by external projects is not working due a problem with minikube.
The best solution should be migrate to microk8s for local environments.
More info: https://github.com/go-gitea/gitea/issues/15570

**Comment by angelsanchez** [comment]
We have changed the local deployment to MicroK8s so we can use the latest versions of Gitea.
